# Copy to environment.local.ps1 (ignored by Git) and fill in local-only values.
$env:FENGMAP_APP_NAME = ""
$env:FENGMAP_MAP_ID = "90872"
$env:FENGMAP_KEY = ""
$env:PORT = "3000"
$env:NODE_ENV = "development"
$env:DATABASE_ENGINE = "sqlite"
$env:DEEPSEEK_API_KEY = ""
$env:DEEPSEEK_MODEL = "deepseek-v4-flash"
$env:XFYUN_IAT_APP_ID = ""
$env:XFYUN_IAT_API_KEY = ""
$env:XFYUN_IAT_API_SECRET = ""
$env:XFYUN_TTS_APP_ID = ""
$env:XFYUN_TTS_API_KEY = ""
$env:XFYUN_TTS_API_SECRET = ""
$env:XFYUN_TTS_API_PASSWORD = ""
